version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - SD_API_URL=http://stable-diffusion:7860
    depends_on:
      - stable-diffusion

  stable-diffusion:
    build:
      context: ./stable-diffusion
    ports:
      - "7860:7860"
    volumes:
      - ./sd_models:/app/models/Stable-diffusion
    command: ["python", "launch.py", "--api", "--listen", "--no-download", "--ckpt", "/app/models/Stable-diffusion/revAnimated_v2Rebirth.safetensors"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
